$logsDirectory = Join-Path -Path "$Env:TEMP" -ChildPath 'Logs'
$pastDays = 90

if (-not(Test-Path -Path $logsDirectory)) {
    New-Item -Path $logsDirectory -ItemType Directory
}

function Set-RandomSizeFile {
    <#
    .SYNOPSIS
    Creates a randomly sized file.

    .DESCRIPTION
    Creates a randomly sized file. The random size is generated by multiplying a random number by 1024^2

    .PARAMETER filePath
    The filepath of the randomly sized file to be created.

    .EXAMPLE
    Set-RandomSizeFile -FilePath D:\Logs

    .NOTES
    Best if used inside a for loop.
    #>
    [CmdletBinding()]
    [OutputType([System.Object])]
    param (
        [Parameter(Mandatory = $true)]
        [string]
        $filePath
    )

    $size = Get-Random -Minimum 1 -Maximum 50
    $size = $size * 1024 * 1024
    $file = [System.IO.File]::Open($filePath, 4)
    
    $file.SetLength($size)
    $file.Close()

    Get-Item -Path $file.Name
}

for ($i = 0; $i -lt $pastDays; $i++) {
    $date = (Get-Date).AddDays(-$i)
    $fileName = "u_ex$(date.ToString('yyyyMMdd')).log"
    $filePath = Join-Path -Path $logsDirectory -ChildPath $fileName
    $date | Out-File -FilePath $filePath
    Set-RandomSizeFile -FilePath $filePath

    Get-Item -Path $FilePath | ForEach-Object {
        $_.CreationTime = $date
        $_.LastWriteTime = $date
        $_.LastAccessTime = $date 
    }
}
